#!/usr/bin/env bash
#
# The Custom Startup — Statusline Configurator
#
# Interactive wizard to install and configure any of the three statusline variants.
# All variants share a single statusline.toml config file.
# Supports global (~/.config/the-agentic-startup/) and per-repo (.claude/) installation.
#
# Usage:
#   ./configure-statusline.sh              # interactive
#   ./configure-statusline.sh --global     # skip location question, install globally
#   ./configure-statusline.sh --repo       # skip location question, install per-repo
#   ./configure-statusline.sh --help

set -euo pipefail

# ==============================================================================
# Colors / logging
# ==============================================================================

GREEN='\033[0;32m'
BRIGHT_GREEN='\033[1;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
DIM='\033[2m'
RESET='\033[0m'

info()    { printf "${DIM}→${RESET} %s\n" "$*"; }
warn()    { printf "${YELLOW}!${RESET} %s\n" "$*" >&2; }
error()   { printf "${RED}✗${RESET} %s\n" "$*" >&2; }
success() { printf "${GREEN}✓${RESET} %s\n" "$*"; }
ask()     { printf "${CYAN}?${RESET} %s " "$*"; }
header()  { printf "\n${BRIGHT_GREEN}── %s${RESET}\n" "$*"; }

# ==============================================================================
# Script location
# ==============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VARIANTS_DIR="$SCRIPT_DIR"
GLOBAL_CONFIG_DIR="$HOME/.config/the-agentic-startup"
CLAUDE_SETTINGS="$HOME/.claude/settings.json"

# ==============================================================================
# Helpers
# ==============================================================================

command_exists() { command -v "$1" > /dev/null 2>&1; }

prompt_yn() {
  local question="$1" default="${2:-y}"
  local prompt
  [[ "$default" == "y" ]] && prompt="[Y/n]" || prompt="[y/N]"
  ask "$question $prompt"
  local answer
  read -r answer </dev/tty
  case "$answer" in
    [nN]|[nN][oO]) return 1 ;;
    [yY]|[yY][eE][sS]) return 0 ;;
    "") [[ "$default" == "y" ]] && return 0 || return 1 ;;
    *) return 1 ;;
  esac
}

prompt_choice() {
  local question="$1"; shift
  local options=("$@")
  ask "$question"
  printf '\n'
  local i=1
  for opt in "${options[@]}"; do
    printf "  ${CYAN}%d)${RESET} %s\n" "$i" "$opt"
    (( i++ ))
  done
  ask "Enter number [1-${#options[@]}]:"
  local choice
  read -r choice </dev/tty
  echo "$choice"
}

update_settings_json() {
  local settings_file="$1" script_path="$2"

  # Check if jq is available
  if ! command_exists jq; then
    error "jq is required to update settings.json"
    echo "  macOS:  brew install jq"
    echo "  Ubuntu: sudo apt install jq"
    return 1
  fi

  # Check for existing statusLine config
  if jq -e '.statusLine' "$settings_file" > /dev/null 2>&1; then
    local existing_cmd
    existing_cmd=$(jq -r '.statusLine.command // ""' "$settings_file" 2>/dev/null)
    warn "A statusline is already configured: ${existing_cmd}"
    if ! prompt_yn "Replace it with the new one?" "n"; then
      info "Keeping existing statusline configuration"
      return 0
    fi
  fi

  local tmp_file
  tmp_file=$(mktemp)
  if jq --arg cmd "$script_path" \
    '.statusLine = {"type": "command", "command": $cmd}' \
    "$settings_file" > "$tmp_file"; then
    mv "$tmp_file" "$settings_file"
    success "Statusline configured in $settings_file"
  else
    rm -f "$tmp_file"
    error "Failed to update $settings_file"
    return 1
  fi
}

generate_toml() {
  local toml_path="$1" plan="${2:-pro}" token_limit="${3:-}" budget_mode="${4:-token}"

  cat > "$toml_path" << EOF
# The Custom Startup — Statusline Configuration
# Generated by configure-statusline.sh — edit freely.
# Shared by all statusline variants.
#
# Global:   ~/.config/the-agentic-startup/statusline.toml
# Per-repo: <repo>/.claude/statusline.toml  (overrides global, partial is fine)

# Claude subscription plan
# Options: auto | pro | max5x | max20x | api
plan          = "${plan}"
fallback_plan = "pro"
EOF

  if [[ -n "$token_limit" ]]; then
    cat >> "$toml_path" << EOF

# Manual token limit override (overrides plan default)
token_limit = ${token_limit}
EOF
  fi

  cat >> "$toml_path" << EOF

# Budget bar mode: "token" (enhanced default) | "cost" (standard default)
budget_mode = "${budget_mode}"

# Format string (standard statusline only)
format = "<path> <branch>  <model>  <context>  <session>  <help>"

# Cache TTLs (seconds)
ccusage_cache_ttl = 60
git_cache_ttl     = 15

# Display toggles (enhanced statusline)
show_budget_bar  = true
show_context_bar = true
show_duration    = true
show_git         = true
show_remote_url  = true

[thresholds.context]
warn   = 70
danger = 90

[thresholds.budget]
warn   = 70
danger = 90
EOF

  success "Config written to $toml_path"
}

# ==============================================================================
# Dependency checks
# ==============================================================================

check_dependencies() {
  header "Checking dependencies"

  local missing=()

  command_exists jq      || missing+=("jq")
  command_exists git     || missing+=("git")

  if [[ ${#missing[@]} -gt 0 ]]; then
    warn "Missing required tools: ${missing[*]}"

    local os
    os=$(uname -s)
    case "$os" in
      Darwin)
        echo "  Install with: brew install ${missing[*]}" ;;
      Linux)
        echo "  Install with: sudo apt install ${missing[*]}  (Debian/Ubuntu)"
        echo "            or: sudo dnf install ${missing[*]}  (Fedora/RHEL)" ;;
      MSYS*|CYGWIN*|MINGW*)
        echo "  Install with: winget install jqlang.jq" ;;
    esac
    echo ""
    if ! prompt_yn "Continue anyway?" "n"; then
      exit 1
    fi
  else
    success "All base dependencies present"
  fi
}

check_ccusage() {
  if ! command_exists bun; then
    warn "bun not found — token budget bar will be unavailable"
    echo "  Install: curl -fsSL https://bun.sh/install | bash"
    CCUSAGE_OK=false; return 1
  fi
  if ! bun x ccusage --version > /dev/null 2>&1; then
    warn "ccusage not found — token budget bar will be unavailable"
    echo "  Install: bun x ccusage"
    CCUSAGE_OK=false; return 1
  fi
  success "ccusage available"
  CCUSAGE_OK=true; return 0
}

check_starship() {
  if command_exists starship; then
    success "Starship detected: $(starship --version 2>/dev/null | head -1)"
    STARSHIP_OK=true; return 0
  else
    warn "Starship not installed — Starship variant will be unavailable"
    echo "  Install: curl -sS https://starship.rs/install.sh | sh"
    STARSHIP_OK=false; return 1
  fi
}

# Run ALL requirement checks upfront and populate *_OK variables.
# Must be called before any user questions.
check_all_requirements() {
  tcs_header "Checking requirements"

  check_dependencies    # jq, git — hard requirements
  check_ccusage         # optional, sets CCUSAGE_OK
  check_starship        # optional, sets STARSHIP_OK

  echo ""
  echo "  Available variants:"
  echo "  Enhanced : $(  [[ "$CCUSAGE_OK"  == "true" ]] && echo "✓ ready" || echo "⚠ ready (token bar disabled — ccusage missing)")"
  echo "  Starship : $(  [[ "$STARSHIP_OK" == "true" ]] && echo "✓ ready" || echo "✗ unavailable (starship not installed)")"
  echo "  Standard : ✓ ready"
  echo ""
}

# ==============================================================================
# Variant selection
# ==============================================================================

select_variant() {
  tcs_header "Choose statusline variant"

  local ccusage_note="" starship_note=""
  [[ "$CCUSAGE_OK"  != "true" ]] && ccusage_note=" ${YELLOW}(token bar disabled)${RESET}"
  [[ "$STARSHIP_OK" != "true" ]] && starship_note=" ${RED}(unavailable — starship not installed)${RESET}"

  echo -e "  ${CYAN}1)${RESET} Enhanced  — Two-line: git info, context + token budget bars, OSC 8 links${ccusage_note}"
  echo ""
  echo -e "  ${CYAN}2)${RESET} Starship  — Your existing Starship prompt extended with Claude data${starship_note}"
  echo ""
  echo    "  ${CYAN}3)${RESET} Standard  — Single-line, placeholder-based, lightweight"
  echo ""

  ask "Select variant [1-3]:"
  local choice
  read -r choice </dev/tty

  case "$choice" in
    1) VARIANT="enhanced" ;;
    2)
      if [[ "$STARSHIP_OK" != "true" ]]; then
        tcs_error "Starship is not installed. Install it first, then re-run this configurator."
        exit 1
      fi
      VARIANT="starship"
      ;;
    3) VARIANT="standard" ;;
    *)
      warn "Invalid choice, defaulting to Enhanced"
      VARIANT="enhanced"
      ;;
  esac
}

# ==============================================================================
# Install location
# ==============================================================================

select_location() {
  header "Installation scope"

  echo "  ${CYAN}1)${RESET} Global  — applies to all Claude Code sessions (~/.claude/settings.json)"
  echo "  ${CYAN}2)${RESET} Repo    — applies only to this repository (.claude/settings.json)"
  echo ""

  ask "Select scope [1-2]:"
  local choice
  read -r choice </dev/tty

  case "$choice" in
    1) SCOPE="global" ;;
    2) SCOPE="repo" ;;
    *)
      warn "Invalid choice, defaulting to Global"
      SCOPE="global"
      ;;
  esac
}

# ==============================================================================
# Plan selection (enhanced variant only)
# ==============================================================================

select_plan() {
  header "Claude subscription plan"
  echo "  This sets the token budget limit for the budget bar."
  echo ""
  echo "  ${CYAN}1)${RESET} Pro     ($20/mo)  — ~44,000 tokens / 5h window"
  echo "  ${CYAN}2)${RESET} Max 5x  ($100/mo) — ~88,000 tokens / 5h window"
  echo "  ${CYAN}3)${RESET} Max 20x ($200/mo) — ~220,000 tokens / 5h window"
  echo "  ${CYAN}4)${RESET} Custom  — enter token limit manually"
  echo ""

  ask "Select plan [1-4]:"
  local choice
  read -r choice </dev/tty

  PLAN_CUSTOM_LIMIT=""
  case "$choice" in
    1) PLAN="pro" ;;
    2) PLAN="max5x" ;;
    3) PLAN="max20x" ;;
    4)
      PLAN="pro"
      ask "Enter token limit (e.g. 44000):"
      read -r PLAN_CUSTOM_LIMIT </dev/tty
      ;;
    *)
      warn "Invalid choice, defaulting to Pro"
      PLAN="pro"
      ;;
  esac

  # Budget mode
  echo ""
  echo "  Budget bar display mode:"
  echo "  ${CYAN}1)${RESET} token — show token usage vs plan limit  (recommended for Enhanced)"
  echo "  ${CYAN}2)${RESET} cost  — show USD per session             (standard statusline default)"
  echo ""
  ask "Select mode [1-2, default: 1]:"
  local mode_choice
  read -r mode_choice </dev/tty
  case "$mode_choice" in
    2) BUDGET_MODE="cost" ;;
    *) BUDGET_MODE="token" ;;
  esac
}

# ==============================================================================
# Main install flow
# ==============================================================================

install_enhanced() {
  tcs_header "Installing Enhanced Statusline"

  [[ "$CCUSAGE_OK" != "true" ]] && \
    tcs_warn "Token budget bar disabled until ccusage is available"

  select_plan

  # Determine config and script destinations
  local script_src="$VARIANTS_DIR/the-custom-startup-statusline-enhanced.sh"
  local settings_file

  if [[ "$SCOPE" == "global" ]]; then
    local script_dest="$GLOBAL_CONFIG_DIR/the-custom-startup-statusline-enhanced.sh"
    local toml_dest="$GLOBAL_CONFIG_DIR/statusline.toml"
    settings_file="$CLAUDE_SETTINGS"
    mkdir -p "$GLOBAL_CONFIG_DIR"
  else
    local repo_root
    repo_root=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
    local script_dest="$repo_root/.claude/the-custom-startup-statusline-enhanced.sh"
    local toml_dest="$repo_root/.claude/statusline.toml"
    settings_file="$repo_root/.claude/settings.json"
    mkdir -p "$repo_root/.claude"
    # Initialize settings.json if missing
    [[ ! -f "$settings_file" ]] && echo '{}' > "$settings_file"
  fi

  # Copy script
  info "Installing script..."
  cp "$script_src" "$script_dest"
  chmod +x "$script_dest"
  success "Script installed: $script_dest"

  # Generate TOML (preserve existing)
  if [[ -f "$toml_dest" ]]; then
    if prompt_yn "Config already exists at $toml_dest — overwrite?" "n"; then
      generate_toml "$toml_dest" "$PLAN" "$PLAN_CUSTOM_LIMIT" "$BUDGET_MODE"
    else
      info "Preserving existing config"
    fi
  else
    generate_toml "$toml_dest" "$PLAN" "$PLAN_CUSTOM_LIMIT" "$BUDGET_MODE"
  fi

  # Update settings.json
  info "Updating settings.json..."
  update_settings_json "$settings_file" "$script_dest"
}

install_starship() {
  tcs_header "Installing Starship Statusline Bridge"
  # Starship availability already confirmed in check_all_requirements + select_variant

  local script_src="$VARIANTS_DIR/the-custom-startup-statusline-starship.sh"
  local settings_file

  if [[ "$SCOPE" == "global" ]]; then
    local script_dest="$GLOBAL_CONFIG_DIR/the-custom-startup-statusline-starship.sh"
    settings_file="$CLAUDE_SETTINGS"
    mkdir -p "$GLOBAL_CONFIG_DIR"
  else
    local repo_root
    repo_root=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
    local script_dest="$repo_root/.claude/the-custom-startup-statusline-starship.sh"
    settings_file="$repo_root/.claude/settings.json"
    mkdir -p "$repo_root/.claude"
    [[ ! -f "$settings_file" ]] && echo '{}' > "$settings_file"
  fi

  info "Installing bridge script..."
  cp "$script_src" "$script_dest"
  chmod +x "$script_dest"
  success "Script installed: $script_dest"

  echo ""
  echo "  ${YELLOW}Next step:${RESET} Add env_var modules to ~/.config/starship.toml"
  echo "  See: docs/statusline-starship-reddit.md for the full setup guide."
  echo ""

  update_settings_json "$settings_file" "$script_dest"
}

install_standard() {
  tcs_header "Installing Standard Statusline"

  local script_src="$VARIANTS_DIR/statusline.sh"
  local settings_file

  if [[ "$SCOPE" == "global" ]]; then
    local script_dest="$GLOBAL_CONFIG_DIR/the-custom-startup-statusline.sh"
    local toml_dest="$GLOBAL_CONFIG_DIR/statusline.toml"
    settings_file="$CLAUDE_SETTINGS"
    mkdir -p "$GLOBAL_CONFIG_DIR"
  else
    local repo_root
    repo_root=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
    local script_dest="$repo_root/.claude/the-custom-startup-statusline.sh"
    local toml_dest="$repo_root/.claude/statusline.toml"
    settings_file="$repo_root/.claude/settings.json"
    mkdir -p "$repo_root/.claude"
    [[ ! -f "$settings_file" ]] && echo '{}' > "$settings_file"
  fi

  info "Installing script..."
  cp "$script_src" "$script_dest"
  chmod +x "$script_dest"
  success "Script installed: $script_dest"

  # Copy TOML if not present
  local toml_src="$VARIANTS_DIR/statusline.toml"
  if [[ ! -f "$toml_dest" && -f "$toml_src" ]]; then
    cp "$toml_src" "$toml_dest"
    success "Config created: $toml_dest"
  elif [[ -f "$toml_dest" ]]; then
    info "Config already exists, preserving: $toml_dest"
  fi

  update_settings_json "$settings_file" "$script_dest"
}

# ==============================================================================
# Argument parsing
# ==============================================================================

SCOPE=""
VARIANT=""
PLAN="pro"
PLAN_CUSTOM_LIMIT=""
BUDGET_MODE="token"
CCUSAGE_OK=false
STARSHIP_OK=false

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --global) SCOPE="global" ;;
      --repo)   SCOPE="repo" ;;
      --help|-h)
        cat << EOF
The Custom Startup — Statusline Configurator

Usage: configure-statusline.sh [--global | --repo] [--help]

Options:
  --global   Install globally (~/.claude/settings.json)
  --repo     Install per-repo (.claude/settings.json in current git repo)
  --help     Show this help

Without flags, runs in interactive mode.
EOF
        exit 0
        ;;
      *) warn "Unknown option: $1" ;;
    esac
    shift
  done
}

# ==============================================================================
# Entry point
# ==============================================================================

main() {
  parse_args "$@"

  printf "${BRIGHT_GREEN}"
  echo "┌─────────────────────────────────────┐"
  echo "│  The Custom Startup Statusline Setup │"
  echo "└─────────────────────────────────────┘"
  printf "${RESET}"
  echo ""

  # ALL requirement checks before any user questions
  check_all_requirements

  [[ -z "$SCOPE" ]]   && select_location
  [[ -z "$VARIANT" ]] && select_variant

  case "$VARIANT" in
    enhanced) install_enhanced ;;
    starship) install_starship ;;
    standard) install_standard ;;
  esac

  echo ""
  printf "${BRIGHT_GREEN}Done!${RESET} Statusline will update after the next Claude response.\n"
  echo ""
  echo "  ${DIM}Re-run this script anytime to switch variants or change settings.${RESET}"
}

main "$@"
